export type PageEntry = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDesc: string;
  type: "pillar" | "cluster" | "comparison" | "tool" | "blog" | "legal" | "service" | "support";
  parent: string;
  datePublished: string;
  dateModified: string;
  priority: number;
  changeFrequency: "daily" | "weekly" | "monthly" | "yearly";
};

export const PAGES: PageEntry[] = [
  // Phase 1 — Existing pages
  { slug: "/", title: "EIN Number for Non-Residents", metaTitle: "EIN Number for Non-Residents | $49 Fast Service | ein.so", metaDesc: "Get your EIN as a non-US resident. We file your SS-4 form and deliver your EIN fast. Standard $49. Express $97.", type: "service", parent: "", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 1.0, changeFrequency: "weekly" },
  { slug: "/apply/", title: "Apply for EIN", metaTitle: "Apply for EIN | Non-Resident Service | $49 Standard $97 Express", metaDesc: "Apply for your EIN as a non-US resident. Standard $49 (14 days) or Express $97 (7 days). No SSN required. We handle the IRS fax process.", type: "service", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/about/", title: "About ein.so", metaTitle: "About ein.so | EIN Service for Non-Residents", metaDesc: "ein.so helps non-US residents get their EIN fast. We file Form SS-4 by fax with the IRS so you don't have to.", type: "support", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.5, changeFrequency: "monthly" },
  { slug: "/faq/", title: "Frequently Asked Questions", metaTitle: "EIN FAQ | Common Questions About EIN Numbers for Non-Residents", metaDesc: "Answers to 37+ common questions about EIN numbers, the application process, non-resident requirements, and what happens after you get your EIN.", type: "support", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/contact/", title: "Contact Us", metaTitle: "Contact ein.so | WhatsApp & Email Support", metaDesc: "Get in touch with ein.so via WhatsApp or email. We respond within 2 hours during business hours.", type: "support", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.4, changeFrequency: "monthly" },
  { slug: "/what-is-ein/", title: "What Is an EIN Number?", metaTitle: "What Is an EIN Number? Complete Guide 2026 | ein.so", metaDesc: "An EIN (Employer Identification Number) is a 9-digit number the IRS assigns to businesses. Learn what an EIN is, who needs one, and how to get yours.", type: "pillar", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/how-to-get-ein/", title: "How to Get an EIN Number", metaTitle: "How to Get an EIN Number in 2026 | Step-by-Step Guide", metaDesc: "Get your EIN in 3 ways: online (US residents), by fax (non-residents), or by phone. Step-by-step guide with Form SS-4 instructions.", type: "pillar", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/ein-vs-itin/", title: "EIN vs ITIN", metaTitle: "EIN vs ITIN: What's the Difference? (2026 Guide)", metaDesc: "An EIN identifies your business. An ITIN identifies you as an individual taxpayer. Learn which one you need and when you might need both.", type: "pillar", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/ein-lookup/", title: "EIN Lookup", metaTitle: "EIN Lookup: How to Find Any EIN Number (2026)", metaDesc: "There is no universal EIN lookup tool. Use IRS Tax Exempt Search, SEC EDGAR, state registries, or call the IRS to find an EIN.", type: "pillar", parent: "/", datePublished: "2026-03-31", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },

  // Legal
  { slug: "/privacy/", title: "Privacy Policy", metaTitle: "Privacy Policy | ein.so", metaDesc: "ein.so privacy policy. How we collect, use, and protect your personal information.", type: "legal", parent: "/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.2, changeFrequency: "yearly" },
  { slug: "/terms/", title: "Terms of Service", metaTitle: "Terms of Service | ein.so", metaDesc: "ein.so terms of service. Service terms, disclaimers, and refund policy for our EIN application service.", type: "legal", parent: "/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.2, changeFrequency: "yearly" },

  // Phase 2 — New pages
  { slug: "/who-needs-ein/", title: "Who Needs an EIN?", metaTitle: "Who Needs an EIN? Complete Eligibility Guide (2026)", metaDesc: "LLCs, corporations, nonprofits, partnerships, sole proprietors with employees, and non-resident entrepreneurs all need an EIN. Check if you qualify.", type: "pillar", parent: "/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/what-can-you-do-with-ein/", title: "What Can You Do With an EIN?", metaTitle: "What Can You Do With an EIN? 8 Essential Uses (2026)", metaDesc: "Use your EIN to open a US bank account, file taxes, hire employees, apply for business credit, and accept payments on Amazon, Shopify, Stripe, and PayPal.", type: "pillar", parent: "/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/ss4-form-guide/", title: "IRS Form SS-4 Guide", metaTitle: "IRS Form SS-4 Guide: Line-by-Line Instructions (2026)", metaDesc: "Complete guide to filling out IRS Form SS-4 for your EIN application. Line-by-line instructions for non-residents filing by fax.", type: "cluster", parent: "/how-to-get-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/ein-without-ssn/", title: "How to Get an EIN Without an SSN", metaTitle: "How to Get an EIN Without an SSN (2026 Guide)", metaDesc: "Non-US residents can get an EIN without a Social Security Number. File Form SS-4 by fax with the IRS using your foreign passport.", type: "cluster", parent: "/how-to-get-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/ein-processing-time/", title: "EIN Processing Time", metaTitle: "EIN Processing Time: How Long Does It Take? (2026)", metaDesc: "Online EIN: instant. Fax (non-residents): 4-7 business days. Phone: same day. Mail: 4-6 weeks. Get Express processing in 7 days with ein.so.", type: "cluster", parent: "/how-to-get-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-llc/", title: "EIN for LLC", metaTitle: "EIN for LLC: Do You Need One? How to Apply (2026)", metaDesc: "Every LLC needs an EIN for tax filing, banking, and hiring. Learn how to get an EIN for your LLC in 2026, including BOI filing requirements.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/ein-for-non-residents/", title: "EIN for Non-US Residents", metaTitle: "EIN for Non-US Residents: How to Apply From Abroad (2026)", metaDesc: "Non-US residents can get an EIN by filing Form SS-4 by fax. No SSN required. ein.so handles the entire process for $49.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.9, changeFrequency: "monthly" },
  { slug: "/ein-for-amazon-sellers/", title: "EIN for Amazon Sellers", metaTitle: "EIN for Amazon Sellers: Required for FBA & Seller Central (2026)", metaDesc: "Amazon requires an EIN for Seller Central tax interviews. Non-US Amazon FBA sellers need to file Form SS-4 by fax. Get yours in 7 days.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/ein-vs-ssn/", title: "EIN vs SSN", metaTitle: "EIN vs SSN: What's the Difference? (2026 Comparison)", metaDesc: "An EIN identifies a business entity. An SSN identifies an individual. Non-residents without an SSN can still get an EIN for their US business.", type: "comparison", parent: "/ein-vs-itin/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-bank-account/", title: "EIN for Bank Account", metaTitle: "EIN for Bank Account: Open a US Business Account (2026)", metaDesc: "You need an EIN to open a US business bank account. Mercury, Relay, and Wise accept EINs from non-residents. Here's how to get started.", type: "cluster", parent: "/what-can-you-do-with-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/boi-filing/", title: "BOI Filing", metaTitle: "BOI Filing: Beneficial Ownership Information Report (2026)", metaDesc: "Every LLC and corporation must file a BOI report with FinCEN. Failure to file results in $500/day penalties. Learn requirements and deadlines.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.8, changeFrequency: "monthly" },
  { slug: "/boi-filing-deadline/", title: "BOI Filing Deadline", metaTitle: "BOI Filing Deadline 2026: When Is Your Report Due?", metaDesc: "BOI filing deadlines: existing companies by Jan 1, 2025. New companies within 90 days of formation. Late filing penalty: $500/day.", type: "cluster", parent: "/boi-filing/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },

  // Phase 3 — Business types
  { slug: "/ein-for-sole-proprietor/", title: "EIN for Sole Proprietor", metaTitle: "EIN for Sole Proprietor: Do You Need One? (2026)", metaDesc: "Sole proprietors need an EIN if they hire employees, file excise tax returns, or have a Keogh plan. Learn when and how to apply.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-corporation/", title: "EIN for Corporation", metaTitle: "EIN for Corporation: How to Apply (2026 Guide)", metaDesc: "Every corporation needs an EIN for tax filing, payroll, and banking. Apply online (US) or by fax (non-residents) using Form SS-4.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-nonprofit/", title: "EIN for Nonprofit", metaTitle: "EIN for Nonprofit Organization: How to Apply (2026)", metaDesc: "Every nonprofit needs an EIN before applying for 501(c)(3) tax-exempt status. Apply with Form SS-4 selecting 'Other nonprofit organization.'", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-partnership/", title: "EIN for Partnership", metaTitle: "EIN for Partnership: Required for All Partnerships (2026)", metaDesc: "Every partnership needs an EIN. Required for Form 1065 filing, opening bank accounts, and issuing K-1s to partners.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-trust/", title: "EIN for Trust", metaTitle: "EIN for Trust: When Trusts Need an EIN (2026)", metaDesc: "Irrevocable trusts always need an EIN. Revocable trusts need one after the grantor dies. Learn which trusts need an EIN and how to apply.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-estate/", title: "EIN for Estate", metaTitle: "EIN for Estate: How to Get One for a Deceased Person (2026)", metaDesc: "An estate needs its own EIN for tax filing and asset distribution. The executor applies using Form SS-4 after the individual passes.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-scorp/", title: "EIN for S-Corp", metaTitle: "EIN for S-Corp: How to Apply After S-Corp Election (2026)", metaDesc: "S-Corps use the same EIN as the original entity. You do not need a new EIN after filing Form 2553 for S-Corp election.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },

  // Phase 3 — Audience segments
  { slug: "/ein-for-shopify-sellers/", title: "EIN for Shopify Sellers", metaTitle: "EIN for Shopify Sellers: Tax Setup Guide (2026)", metaDesc: "Shopify requires tax information for US sales. Non-US Shopify sellers need an EIN for tax compliance and payment processing.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-freelancers/", title: "EIN for Freelancers", metaTitle: "EIN for Freelancers: Protect Your SSN on W-9 Forms (2026)", metaDesc: "Freelancers use an EIN on W-9 forms instead of their SSN. Protect your identity and separate business from personal taxes.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-real-estate-investors/", title: "EIN for Real Estate Investors", metaTitle: "EIN for Real Estate Investors: LLC & FIRPTA Guide (2026)", metaDesc: "Real estate investors need an EIN for their LLC, rental income reporting, and FIRPTA compliance. Non-resident investors: apply by fax.", type: "cluster", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },

  // Phase 3 — Platform/use case
  { slug: "/ein-for-paypal/", title: "EIN for PayPal", metaTitle: "EIN for PayPal Business Account: Setup Guide (2026)", metaDesc: "PayPal requires an EIN for business accounts. Non-residents need an EIN to receive US payments through PayPal.", type: "cluster", parent: "/what-can-you-do-with-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-stripe/", title: "EIN for Stripe", metaTitle: "EIN for Stripe: Accept US Payments as Non-Resident (2026)", metaDesc: "Stripe requires an EIN for US-based payment processing. Non-residents can use Atlas or provide an EIN directly.", type: "cluster", parent: "/what-can-you-do-with-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-credit/", title: "EIN for Business Credit", metaTitle: "EIN for Business Credit: Build Credit Without SSN (2026)", metaDesc: "Use your EIN to build business credit separate from personal credit. Open business credit cards and establish a Dun & Bradstreet profile.", type: "cluster", parent: "/what-can-you-do-with-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-hiring-employees/", title: "EIN for Hiring Employees", metaTitle: "EIN for Hiring Employees: Payroll Tax Requirements (2026)", metaDesc: "You must have an EIN before hiring your first employee. Required for Form 941, W-2s, and state payroll tax registration.", type: "cluster", parent: "/what-can-you-do-with-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },

  // Phase 3 — Process/comparison
  { slug: "/ein-rejection-guide/", title: "EIN Rejection Guide", metaTitle: "EIN Application Rejected? Fix & Reapply Guide (2026)", metaDesc: "EIN rejections happen due to duplicate applications, incorrect SS-4 data, or name mismatches. Learn how to fix errors and reapply.", type: "cluster", parent: "/how-to-get-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-lookup-free/", title: "Free EIN Lookup", metaTitle: "Free EIN Lookup: 5 Ways to Find an EIN Number (2026)", metaDesc: "Find any EIN for free using IRS Tax Exempt Search, SEC EDGAR, state business registries, or by calling the IRS directly.", type: "cluster", parent: "/ein-lookup/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-number-format/", title: "EIN Number Format", metaTitle: "EIN Number Format Explained: XX-XXXXXXX (2026)", metaDesc: "An EIN is formatted as XX-XXXXXXX (9 digits with a hyphen after the first 2). The first 2 digits indicate the IRS campus that issued it.", type: "cluster", parent: "/what-is-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-vs-tax-id/", title: "EIN vs Tax ID", metaTitle: "EIN vs Tax ID: Are They the Same? (2026)", metaDesc: "An EIN is one type of Tax ID. Tax ID is the umbrella term covering EIN, SSN, and ITIN. Learn the differences and which one you need.", type: "comparison", parent: "/ein-vs-itin/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-vs-tin/", title: "EIN vs TIN", metaTitle: "EIN vs TIN: What's the Difference? (2026)", metaDesc: "TIN (Taxpayer Identification Number) is the general term. EIN, SSN, and ITIN are all types of TINs. Learn which one your business needs.", type: "comparison", parent: "/ein-vs-itin/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },

  // Phase 3 — Compliance
  { slug: "/boi-penalties/", title: "BOI Filing Penalties", metaTitle: "BOI Filing Penalties: $500/Day Fine for Non-Compliance (2026)", metaDesc: "Failing to file your BOI report results in $500/day civil penalties and up to $10,000 in criminal fines. Learn how to avoid penalties.", type: "cluster", parent: "/boi-filing/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/s-corp-election/", title: "S-Corp Election", metaTitle: "S-Corp Election: Form 2553 Filing Guide (2026)", metaDesc: "File Form 2553 to elect S-Corp status. Must file within 75 days of formation or by March 15 for existing corps. Reduces self-employment tax.", type: "cluster", parent: "/ein-for-corporation/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },

  // Phase 4 — Country pages
  { slug: "/ein-for-india/", title: "EIN for Indian Entrepreneurs", metaTitle: "EIN for Indian Entrepreneurs: Apply From India (2026)", metaDesc: "Indian entrepreneurs can get a US EIN by filing Form SS-4 by fax. No SSN or US address required. ein.so handles the process for $49.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-canada/", title: "EIN for Canadians", metaTitle: "EIN for Canadians: Cross-Border Business Guide (2026)", metaDesc: "Canadian entrepreneurs expanding to the US need an EIN. Apply by fax using Form SS-4 with your Canadian passport.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/ein-for-uk/", title: "EIN for UK Residents", metaTitle: "EIN for UK Residents: US Business Setup Guide (2026)", metaDesc: "UK entrepreneurs can get a US EIN for their American business. File Form SS-4 by fax using your UK passport.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-pakistan/", title: "EIN for Pakistani Entrepreneurs", metaTitle: "EIN for Pakistani Entrepreneurs: Apply From Pakistan (2026)", metaDesc: "Pakistani entrepreneurs can get a US EIN for Amazon FBA, freelancing, and e-commerce. No SSN or US visit required.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-nigeria/", title: "EIN for Nigerian Entrepreneurs", metaTitle: "EIN for Nigerian Entrepreneurs: Apply From Nigeria (2026)", metaDesc: "Nigerian entrepreneurs can get a US EIN for e-commerce, freelancing, and tech businesses. Apply by fax using your Nigerian passport.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-germany/", title: "EIN for German Entrepreneurs", metaTitle: "EIN for German Entrepreneurs: US Market Entry (2026)", metaDesc: "German entrepreneurs expanding to the US need an EIN for Amazon FBA, LLC formation, and US banking.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-china/", title: "EIN for Chinese Entrepreneurs", metaTitle: "EIN for Chinese Entrepreneurs: US Business Guide (2026)", metaDesc: "Chinese entrepreneurs selling on Amazon US need an EIN. Apply by fax using your Chinese passport and Form SS-4.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-philippines/", title: "EIN for Filipino Entrepreneurs", metaTitle: "EIN for Filipino Entrepreneurs: Apply From Philippines (2026)", metaDesc: "Filipino freelancers and entrepreneurs can get a US EIN for Upwork, Amazon, and e-commerce businesses.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-mexico/", title: "EIN for Mexican Entrepreneurs", metaTitle: "EIN for Mexican Entrepreneurs: Cross-Border Guide (2026)", metaDesc: "Mexican entrepreneurs can get a US EIN for cross-border e-commerce and Amazon FBA. Apply by fax with your Mexican passport.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-brazil/", title: "EIN for Brazilian Entrepreneurs", metaTitle: "EIN for Brazilian Entrepreneurs: US Business Guide (2026)", metaDesc: "Brazilian entrepreneurs expanding to the US market need an EIN for Amazon, Shopify, and US banking.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },
  { slug: "/ein-for-bangladesh/", title: "EIN for Bangladeshi Entrepreneurs", metaTitle: "EIN for Bangladeshi Entrepreneurs: Apply From Bangladesh (2026)", metaDesc: "Bangladeshi freelancers and e-commerce sellers can get a US EIN without an SSN. ein.so handles the IRS fax process.", type: "cluster", parent: "/ein-for-non-residents/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.6, changeFrequency: "monthly" },

  // Phase 4 — Tools
  { slug: "/tools/ein-eligibility-checker/", title: "EIN Eligibility Checker", metaTitle: "Free EIN Eligibility Checker: Do You Need an EIN? (2026)", metaDesc: "Answer 5 questions to find out if you need an EIN. Free tool for business owners and non-residents.", type: "tool", parent: "/who-needs-ein/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/tools/ss4-form-helper/", title: "SS-4 Form Helper", metaTitle: "Free SS-4 Form Helper: Line-by-Line Guide (2026)", metaDesc: "Fill out IRS Form SS-4 correctly with our free line-by-line helper. Designed for non-residents applying for an EIN.", type: "tool", parent: "/ss4-form-guide/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
  { slug: "/tools/ein-processing-calculator/", title: "EIN Processing Time Calculator", metaTitle: "EIN Processing Time Calculator: When Will You Get Your EIN?", metaDesc: "Calculate your EIN processing time based on application method. Compare Standard vs Express timelines.", type: "tool", parent: "/ein-processing-time/", datePublished: "2026-04-13", dateModified: "2026-04-13", priority: 0.7, changeFrequency: "monthly" },
];
